# Generated by Django 4.1.7 on 2023-02-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_stipe_user_id_stripeuser_stripe_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeUser',
        ),
    ]
