# Generated by Django 4.1.7 on 2023-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_order_checkout_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_session',
            field=models.CharField(max_length=200),
        ),
    ]
